name: render page
on:
  push:
    branches:
      - main
      - 28-render-page-fails-with-latest-version-of-mkdocs-mkdocs_material-953
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: |
          pip install setuptools mkdocs-material mkdocs-bibtex neoteroi-mkdocs mkdocs-video
          mkdocs gh-deploy --force
